# Formatted for the JetBrains REST client
# See https://www.jetbrains.com/help/rider/Http_client_in__product__code_editor.html

@HostAddress = https://localhost:7145
@ClientId = 00000000-0000-0000-0000-000000000000
@InvalidClientId = FFFFFFFF-0000-0000-0000-000000000000
@ApiKey = client-api-key-1
@InvalidApiKey = invalid-api-key

// ===================
// == ERROR TESTING == 

### GET (HTTP 401 Unauthorized) invalid Client ID
GET {{HostAddress}}/batches
Content-Type: application/json
X-Client-Id: {{InvalidClientId}}
X-API-Key: {{ApiKey}}

### POST (HTTP 401 Unauthorized) invalid Client ID
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{InvalidClientId}}
X-API-Key: {{ApiKey}}

[]

### GET (HTTP 401 Unauthorized) incorrect API key
GET {{HostAddress}}/batches
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{InvalidApiKey}}

### POST (HTTP 401 Unauthorized) incorrect API key
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{InvalidApiKey}}

[]

### (HTTP 401 Unauthorized) missing Client ID
GET {{HostAddress}}/batches
Content-Type: application/json
X-API-Key: {{ApiKey}}

### (HTTP 401 Unauthorized) missing API key
GET {{HostAddress}}/batches
Content-Type: application/json
X-Client-Id: {{ClientId}}

### (HTTP 400 Bad Request) missing Batch Request
POST {{HostAddress}}/batch/
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

### (HTTP 400 Bad Request) empty Batch Request
POST {{HostAddress}}/batch/
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

{}

### (HTTP 400 Bad Request) empty Batch ID
POST {{HostAddress}}/batch/
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

{
  "BatchId": ""
}

### (HTTP 400 Bad Request) missing "from" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) empty "from" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) missing "recipients" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) empty "recipients" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) empty value in the "recipients" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      ""
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) empty value in the "copyRecipients" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      ""
    ],
    "subject": "-",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) missing "subject" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) empty "subject" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) extra long "subject" field (201 characters)
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------",
    "body": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) missing "body" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) empty "body" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "",
    "isHtml": false
  }
]

### (HTTP 400 Bad Request) missing "isHtml" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-"
  }
]

### (HTTP 400 Bad Request) incorrectly formatted "isHtml" field
POST {{HostAddress}}/add
Content-Type: application/json
X-Client-Id: {{ClientId}}
X-API-Key: {{ApiKey}}

[
  {
    "from": "test@example.net",
    "recipients": [
      "test@example.org"
    ],
    "copyRecipients": [
      "test@example.com"
    ],
    "subject": "-",
    "body": "-",
    "isHtml": "false"
  }
]
