# See https://marketplace.visualstudio.com/items/?itemName=humao.rest-client

@HostAddress = https://localhost:7145
@ApiKey = client-api-key-1
@InvalidApiKey = invalid-api-key

### Check health.
GET {{HostAddress}}/health
Accept: application/json

###

# @name addTasks
POST {{HostAddress}}/add
Content-Type: application/json
X-API-Key: {{ApiKey}}

[
  {
    "recipients": [
      "test1@example.com",
      "test1cc@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 1",
    "body": "<h1>Test Email 1</h1><p>HTML content for email 1</p>",
    "isHtml": true
  },
  {
    "recipients": [
      "test2@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 2",
    "body": "Plain text content for email 2",
    "isHtml": false
  },
  {
    "recipients": [
      "test3@example.com",
      "test3cc@example.com"
    ],
    "from": "",
    "subject": "Test Email 3",
    "body": "<h1>Test Email 3</h1><p>HTML content for email 3</p>",
    "isHtml": true
  },
  {
    "recipients": [
      "test4@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 4",
    "body": "Plain text content for email 4",
    "isHtml": false
  }
]

###

@batchId = {{addTasks.response.body.batchId}}

# List all email tasks for returned batch ID.
GET {{HostAddress}}/batch/{{batchId}}
Content-Type: application/json
X-API-Key: {{ApiKey}}

###

# Post an empty array.
POST {{HostAddress}}/add
Content-Type: application/json
X-API-Key: {{ApiKey}}

[]

###

# List all email batches.
GET {{HostAddress}}/batches
Content-Type: application/json
X-API-Key: {{ApiKey}}

###

// == ERROR TESTING == 

# This should fail (HTTP 401 Unauthorized) because of the incorrect API key.
GET {{HostAddress}}/batches
Content-Type: application/json
X-API-Key: {{InvalidApiKey}}

###

# This should fail (HTTP 401 Unauthorized) because of the incorrect API key.
POST {{HostAddress}}/add
Content-Type: application/json
X-API-Key: {{InvalidApiKey}}

[]

###

# This should fail (HTTP 401 Unauthorized) because of the missing API key.
GET {{HostAddress}}/batches
Content-Type: application/json

###

# This should fail (HTTP 400 Bad Request) because of the missing from address.
POST {{HostAddress}}/add
Content-Type: application/json
X-API-Key: {{ApiKey}}

[
  {
    "recipients": [
      "test1@example.com",
      "test1cc@example.com"
    ],
    "subject": "Test Email 1",
    "body": "Text content",
    "isHtml": true
  }
]

###

# This should fail (HTTP 404 Not Found) because of the missing Batch ID.
GET {{HostAddress}}/batch/
Content-Type: application/json
X-API-Key: {{ApiKey}}

###

# This should fail (HTTP 400 Bad Request) because of the missing isHtml field.
POST {{HostAddress}}/add
Content-Type: application/json
X-API-Key: {{ApiKey}}

[
  {
    "recipients": [
      "test1@example.com",
      "test1cc@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 1",
    "body": "Text content"
  }
]
