@EmailQueue_HostAddress = https://localhost:7145
@ApiKey = your-secret-api-key-1

POST {{EmailQueue_HostAddress}}/email
Content-Type: application/json
X-API-Key: {{ApiKey}}

[
  {
    "emailAddress": "test1@example.com",
    "body": "Test email 1"
  },
  {
    "emailAddress": "test2@example.com",
    "body": "Test email 2"
  },
  {
    "emailAddress": "test3@example.com",
    "body": "Test email 3"
  }
]

###

GET {{EmailQueue_HostAddress}}/email
Content-Type: application/json
X-API-Key: {{ApiKey}}

###

@InvalidApiKey = invalid-api-key

GET {{EmailQueue_HostAddress}}/email
Content-Type: application/json
X-API-Key: {{InvalidApiKey}}
