# See https://www.jetbrains.com/help/rider/Http_client_in__product__code_editor.html

@HostAddress = https://localhost:7145
@ApiReadKey = api-read-key-1
@ApiWriteKey = api-write-key-2

### Check health.
GET {{HostAddress}}/health
Accept: application/json

###

# @name addTasks
POST {{HostAddress}}/emailTasks
Content-Type: application/json
X-API-Key: {{ApiWriteKey}}

[
  {
    "recipients": [
      "test1@example.com",
      "test1cc@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 1",
    "body": "<h1>Test Email 1</h1><p>HTML content for email 1</p>",
    "isHtml": true
  },
  {
    "recipients": [
      "test2@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 2",
    "body": "Plain text content for email 2",
    "isHtml": false
  },
  {
    "recipients": [
      "test3@example.com",
      "test3cc@example.com"
    ],
    "from": "",
    "subject": "Test Email 3",
    "body": "<h1>Test Email 3</h1><p>HTML content for email 3</p>",
    "isHtml": true
  },
  {
    "recipients": [
      "test4@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 4",
    "body": "Plain text content for email 4",
    "isHtml": false
  }
]

> {% client.global.set("batchId", response.body.batchId); %}

###

# List all email tasks for returned batch ID.
GET {{HostAddress}}/emailTasks/list/{{batchId}}
Content-Type: application/json
X-API-Key: {{ApiReadKey}}

###

# Post an empty array.
POST {{HostAddress}}/emailTasks
Content-Type: application/json
X-API-Key: {{ApiWriteKey}}

[]

###

# List all email batches.
GET {{HostAddress}}/emailTasks/list
Content-Type: application/json
X-API-Key: {{ApiReadKey}}

###

# This should fail (HTTP 403) because of the incorrect API key.
GET {{HostAddress}}/emailTasks/list
Content-Type: application/json
X-API-Key: {{ApiWriteKey}}

###

# This should fail (HTTP 403) because of the incorrect API key.
POST {{HostAddress}}/emailTasks
Content-Type: application/json
X-API-Key: {{ApiReadKey}}

[]

###

# This should fail (HTTP 401) because of the missing API key.
GET {{HostAddress}}/emailTasks/list
Content-Type: application/json

###

# This should fail (HTTP 400) because of the missing from address.
POST {{HostAddress}}/emailTasks
Content-Type: application/json
X-API-Key: {{ApiWriteKey}}

[
  {
    "recipients": [
      "test1@example.com",
      "test1cc@example.com"
    ],
    "subject": "Test Email 1",
    "body": "Text content",
    "isHtml": true
  }
]

###

# This should fail (HTTP 400) because of the missing isHtml field.
POST {{HostAddress}}/emailTasks
Content-Type: application/json
X-API-Key: {{ApiWriteKey}}

[
  {
    "recipients": [
      "test1@example.com",
      "test1cc@example.com"
    ],
    "from": "test.from@example.net",
    "subject": "Test Email 1",
    "body": "Text content"
  }
]
